name: build

on:
  workflow_dispatch: {}
  release:
    types: [published]
# Ensure the runner can upload release assets
permissions:
  contents: write

jobs:
  generate-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '10.0.x' ]

    steps:
      # Build project
      - uses: actions/checkout@v6
      - name: Setup .NET 10.x
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
          cache: true
          cache-dependency-path: './src/WateryTart.MusicAssistant/packages.lock.json'
      - name: Install dependencies
        run: dotnet restore ./src/WateryTart.MusicAssistant
      - run: dotnet build ./src/WateryTart.MusicAssistant -c Release
      - name: make nupkg
        run: dotnet pack ./src/WateryTart.MusicAssistant

#      # Get a short-lived NuGet API key
#      - name: NuGet login (OIDC → temp API key)
#        uses: NuGet/login@v1
#        id: login
#        with:
#          user: ${{ secrets.NUGET_USER }}
#    
#      # Push the package
#      - name: NuGet push
#        run: dotnet nuget push artifacts/my-sdk.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json