on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple

      - name: Set Version Variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      # Build project
      - uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}
        
      - name: Setup .NET 10.x
        uses: actions/setup-dotnet@v5
        if: ${{ steps.release.outputs.release_created }}
        with:
          dotnet-version: '10.x'
          cache: true
          cache-dependency-path: './src/WateryTart.MusicAssistant/packages.lock.json'
          
      - name: Install dependencies
        run: dotnet restore
        if: ${{ steps.release.outputs.release_created }}
        working-directory: src/WateryTart.MusicAssistant
        
      - run: dotnet build  --configuration Release /p:Version=$VERSION
        if: ${{ steps.release.outputs.release_created }}
        working-directory: src/WateryTart.MusicAssistant
        
      - name: Upload artifact
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-artifact@v6
        with:
          name: WateryTart.MusicAssistant
          path: src/WateryTart.MusicAssistant/bin/Release/
          
      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC â†’ temp API key)
        if: ${{ steps.release.outputs.release_created }}
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
    
      # Push the package
      - name: NuGet push
        if: ${{ steps.release.outputs.release_created && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v') }}
        run: dotnet nuget push src/WateryTart.MusicAssistant/bin/Release/WateryTart.MusicAssistant.$VERSION.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
